### ISSUE TITLE
A different answer gets saved

### ISSUE THREAD

**Issue by rdouma** [suryatech/Quora-Save-To-Pocket#12] opened 2017-08-12 14:39 UTC
When I use the link to save to Pocket, it saves a different answer.

For example, go to https://www.quora.com/profile/Habib-Fanny. Search for North Korea in his answers, and try to save. You get an answer about Syria.

See this video: http://cygno.d.pr/nyEhsh/raFMWV5s

**Comment by rdouma** [comment] 2017-08-12 14:45
Interestingly enough, the link I'm interesting in opens fine in the browser but also just doesn't add correctly when added on getpocket.com. It concerns https://www.quora.com/What-is-the-most-misunderstood-foreign-policy-issue-of-our-day/answer/Habib-Fanny?srid=nys0#

I just get a different answer in Pocket then I get in my browser. It seems to be a Pocket issue.

**Comment by suryatech** [comment] 2017-08-13 03:03
It is unlikely that the extension sends a different link to pocket.
Do you have any other examples or is it specific to this page/answer?

**Comment by rdouma** [comment] 2017-08-14 12:15
For me it consistently happens to basically all answers. It clearly seems
to be a Pocket issue. The behavior is the same as opening the answer page
in a browser and using the default Pocket button. Another video:
http://cygno.d.pr/EzOFXt/2aoztm2s

So not a Save to Pocket issue, my bad. You can close this :-) Thanks!

Cheers,

Remco

On 13 August 2017 at 00:03:03, Surya P (notifications@github.com) wrote:

It is unlikely that the extension sends a different link to pocket.
Do you have any other examples or is it specific to this page/answer?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/suryatech/Quora-Save-To-Pocket/issues/12#issuecomment-322018746>,
or mute the thread

**Comment by suryatech** [comment] 2017-08-14 17:05
Thanks for confirming the root cause. Appreciate your efforts towards this!
I'll go ahead and close this.

**Closed as completed by suryatech** 2017-08-14 17:05 UTC

**Comment by rdouma** [comment] 2017-08-14 17:43
You're very welcome. Thank you for your work!

Cheers,

Remco

On 14 August 2017 at 14:05:59, Surya P (notifications@github.com) wrote:

Thanks for confirming the root cause. Appreciate your efforts towards this!
I'll go ahead and close this.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/suryatech/Quora-Save-To-Pocket/issues/12#issuecomment-322248479>,
or mute the thread
